import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('printing settings provide label dimensions data preview and terminal routing',async()=>{const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),page=source.slice(source.indexOf("case'printing'"),source.indexOf("case'trace'"));for(const token of['data-action="label-design"','widthMm','heightMm','dpi','orientation','labelFields','deviceCode','printerCode','strictRouting','label-preview','assignments','templates'])assert.match(page,new RegExp(token));for(const point of['RECEIVING_SINGLE_USE','WASHING_SESSION','DRY_PACKAGE','FREEZE_DRY_PACKAGE','FREEZE_BOX','FRESH_EXPORT_BOX','CARTON'])assert.match(source,new RegExp(point))});

test('label designer creates a versioned LABEL draft with positioned elements',async()=>{const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),handler=source.slice(source.indexOf("if(a==='label-design')"),source.indexOf("if(a==='label-reprint')"));for(const token of['selectedOptions','xMm','yMm','widthMm','heightMm','templateId','assignment','/api/configurations',"scope:'LABEL'"])assert.match(handler,new RegExp(token.replace('/','\\/')))});

test('an active label template can be loaded, edited, and saved under the same identity',async()=>{const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),wire=source.slice(source.indexOf('const labelDesignForm'),source.indexOf("document.querySelector('[data-export]')"));for(const token of['data-label-template-editor','loadTemplate','templateId.readOnly=true','template.elements','labelAssignments.find','ذخیره ویرایش به‌صورت Draft جدید'])assert.equal(wire.includes(token),true,token)});

test('deleting a label template creates a safe draft and removes dependent printer assignments',async()=>{const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),wire=source.slice(source.indexOf('const labelDesignForm'),source.indexOf("document.querySelector('[data-export]')"));for(const token of['data-label-template-delete','confirm(`قالب','labelTemplates.filter(item=>item.id!==template.id)','labelAssignments.filter(item=>item.templateId!==template.id)',"post('/api/configurations'","scope:'LABEL'",'Draft حذف قالب ساخته شد'])assert.equal(wire.includes(token),true,token)});

test('label preview reacts before save to live size orientation and selected fields',async()=>{const source=await readFile(new URL('../app.js',import.meta.url),'utf8'),page=source.slice(source.indexOf("case'printing'"),source.indexOf("case'trace'")),wire=source.slice(source.indexOf('const labelDesignForm'),source.indexOf("document.querySelector('[data-export]')"));for(const token of['data-label-preview','data-label-preview-meta','پیش‌نمایش زنده'])assert.equal(page.includes(token),true,token);for(const token of['renderLabelPreview','addEventListener(\'input\',renderLabelPreview)','addEventListener(\'change\',renderLabelPreview)','preview.style.aspectRatio','labelFields.selectedOptions'])assert.equal(wire.includes(token),true,token)});
