import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const modules=['dashboard','receiving','inventory','containers','production','quality','packaging','shipments','transfers','tasks','printing','trace','config','master-data','users','overrides','audit','cloud','system'];
const source=()=>readFile(new URL('../app.js',import.meta.url),'utf8');

test('operations console exposes every promised domain module',async()=>{const text=await source();for(const module of modules)assert.ok(text.includes(`['${module}'`)||text.includes(`case'${module}'`),`missing UI module ${module}`)});
test('UI uses site APIs and decodes standard JWT claims',async()=>{const text=await source();for(const endpoint of['inventory','containers','packages','shipments','configurations','audit'])assert.ok(text.includes(`'${endpoint}'`),`missing API integration ${endpoint}`);assert.ok(text.includes('fetch('));assert.ok(text.includes("split('.')[1]"))});
test('operations round 3 UI exposes physical packaging, sorting and customer shipment workflows',async()=>{const text=await source();for(const marker of['packaging-weigh','unit-package','carton-package','carton-scan','data-container-pdf','data-assign-destination','data-action="merge"','sales-order','shipment-scan','start_picking','downloadShipmentDocuments'])assert.ok(text.includes(marker),`missing ${marker}`)});
test('production cycles use scanned carriers and an admin-configured fixed machine',async()=>{const text=await source();assert.match(text,/data-action="cycle"/);assert.match(text,/scannedContainer\(v\.cycleContainerCode/);assert.match(text,/scope==='STATION_MACHINES'.*status==='ACTIVE'/);assert.doesNotMatch(text,/name="machineId"/);for(const action of['start','pause','resume','complete','finish','cancel'])assert.ok(text.includes(action))});
test('re-containerization requires a separately verified destination scan',async()=>{const text=await source();assert.match(text,/destinationContainerCode/);assert.match(text,/scannedContainer\(v\.destinationContainerCode/);assert.doesNotMatch(text,/name="containerId">\$\{options\(containers\)/)});
test('admin configuration exposes real catalogs and identity assignments while harvest is calendar-derived',async()=>{const text=await source();for(const endpoint of['master-data/packageTypes','users','roles','skills'])assert.ok(text.includes(`'${endpoint}'`));for(const action of['master-create','user-role','user-skill','role-create','skill-create'])assert.ok(text.includes(`data-action="${action}"`));assert.doesNotMatch(text,/data-action="harvest-create"/);assert.match(text,/data-badge=/);assert.match(text,/data-revoke-role=/);assert.match(text,/data-revoke-skill=/);assert.match(text,/can\('roles:assign'\)/)});
test('container forms consume active master-data zones, support multiple zones and inline master edits',async()=>{const text=await source();assert.match(text,/case'containers':\{const zones=d\['master-data\/zones'\]/);assert.match(text,/referenceSelect\('زون اولیه','zone',zones\)/);assert.match(text,/name="designatedZones" multiple/);assert.match(text,/data-action="master-update"/);assert.match(text,/data-container-label=/);assert.doesNotMatch(text,/data-master-edit/)});
test('round seven UI exposes fresh export, consumables, tare and container-level cold moves',async()=>{const text=await source();for(const marker of["case'fresh-export'","case'consumables'",'fresh-net-lots','fresh-shipping-boxes','grossWeightKg','tareWeightKg','move-to-cold-storage'])assert.ok(text.includes(marker),marker);assert.doesNotMatch(text,/data-action="move"/);assert.match(text,/active=inv\.filter\(x=>x\.weightKg>0/)});
test('receiving can create and print a basket only before a physical basket scan',async()=>{const text=await source();assert.match(text,/data-print-new-basket>چاپ سبد جدید/);assert.match(text,/printNewBasket\.disabled=!!receivingScan\.value\.trim\(\)/);assert.match(text,/post\('\/api\/containers',\{type:'BASKET'/);assert.match(text,/post\(`\/api\/containers\/\$\{container\.id\}\/label`\)/)});
test('web claims a pending print job before completing it',async()=>{const text=await source(),claim=text.indexOf('print}/claim`'),complete=text.indexOf('print}/${b.dataset.printAction}`');assert.ok(claim>=0&&complete>claim)});
test('production navigation exposes physical carrier movement, QC checklists, attestation, and device registration',async()=>{const text=await source();for(const endpoint of['qc-checklists','devices'])assert.ok(text.includes(`'${endpoint}'`));for(const action of['container-move','qc-checklist','quality','device'])assert.ok(text.includes(`data-action="${action}"`));assert.match(text,/attestation:\{confirmed:true,role:/);assert.match(text,/\/api\/containers\/\$\{v\.moveContainerId\}\/move/);assert.match(text,/data-retire-device=/)});
test('user administration independently regenerates badge PIN',async()=>{const text=await source();assert.match(text,/data-pin=/);assert.match(text,/\/api\/users\/\$\{b\.dataset\.pin\}\/pin/);assert.match(text,/pinAssigned/)});
test('inter-site receipt requires signed manifest package scans and never supplies receiver identity',async()=>{const text=await source();assert.match(text,/JSON مانیفست امضاشده/);assert.match(text,/scanField\([^\n]+,'scannedPackageCodes'\)/);const request=text.match(/post\('\/api\/internal-transfers\/receive',[^;]+/s)?.[0]??'';assert.match(request,/scannedPackageCodes/);assert.doesNotMatch(request,/receivedBy/)});
test('QC UI only offers checklists to batches at their actual stage and uses split cold-room release zones',async()=>{const text=await source();assert.match(text,/const qcStage=batch=>/);assert.match(text,/x\.product===c\.product&&qcStage\(x\)===c\.stage/);assert.match(text,/COLD_ROOM_CLEAN','COLD_ROOM_DIRTY/);assert.doesNotMatch(text,/\['RECEIVING','SORTING','WASH','SLICE'/)});
