import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const modules=['dashboard','receiving','inventory','containers','production','quality','packaging','shipments','transfers','tasks','printing','trace','config','master-data','users','overrides','audit','cloud','system'];
const source=()=>readFile(new URL('../app.js',import.meta.url),'utf8');

test('operations console exposes every promised domain module',async()=>{const text=await source();for(const module of modules)assert.ok(text.includes(`['${module}'`)||text.includes(`case'${module}'`),`missing UI module ${module}`)});
test('UI uses site APIs and decodes standard JWT claims',async()=>{const text=await source();for(const endpoint of['inventory','containers','packages','shipments','configurations','audit'])assert.ok(text.includes(`'${endpoint}'`),`missing API integration ${endpoint}`);assert.ok(text.includes('fetch('));assert.ok(text.includes("split('.')[1]"))});
test('operations round 3 UI exposes physical packaging, sorting and customer shipment workflows',async()=>{const text=await source();for(const marker of['packaging-weigh','unit-package','carton-package','carton-scan','data-container-pdf','data-assign-destination','data-action="merge"','sales-order','shipment-scan','start_picking','downloadShipmentDocuments'])assert.ok(text.includes(marker),`missing ${marker}`)});
test('production cycles use scanned carriers and an admin-configured fixed machine',async()=>{const text=await source();assert.match(text,/data-action="cycle"/);assert.match(text,/scannedContainer\(v\.cycleContainerCode/);assert.match(text,/scope==='STATION_MACHINES'.*status==='ACTIVE'/);assert.doesNotMatch(text,/name="machineId"/);for(const action of['start','pause','resume','complete','finish','cancel'])assert.ok(text.includes(action))});
test('re-containerization requires a separately verified destination scan',async()=>{const text=await source();assert.match(text,/destinationContainerCode/);assert.match(text,/scannedContainer\(v\.destinationContainerCode/);assert.doesNotMatch(text,/name="containerId">\$\{options\(containers\)/)});
test('admin configuration exposes real catalogs and identity assignments while harvest is calendar-derived',async()=>{const text=await source();for(const endpoint of['master-data/packageTypes','users','roles','skills'])assert.ok(text.includes(`'${endpoint}'`));for(const action of['master-create','user-role','user-skill','role-create','skill-create'])assert.ok(text.includes(`data-action="${action}"`));assert.doesNotMatch(text,/data-action="harvest-create"/);assert.match(text,/data-badge=/);assert.match(text,/data-revoke-role=/);assert.match(text,/data-revoke-skill=/);assert.match(text,/can\('roles:assign'\)/)});
test('configuration review shows draft values beside the current active values',async()=>{const text=await source(),page=text.slice(text.indexOf("case'config'"),text.indexOf("case'overrides'"));assert.match(page,/activeByScope/);assert.match(page,/JSON\.stringify\(value\?\?\{\},null,2\)/);assert.match(page,/مقادیر این نسخه/);assert.match(page,/مقادیر ACTIVE فعلی/);for(const scope of['PACKAGING','PRINTING','CONSUMABLES','STATION_MACHINES'])assert.ok(page.includes(`'${scope}'`))});
test('container forms consume active master-data zones, support multiple zones and inline master edits',async()=>{const text=await source();assert.match(text,/case'containers':\{const zones=d\['master-data\/zones'\]/);assert.match(text,/referenceSelect\('زون اولیه','zone',zones\)/);assert.match(text,/name="designatedZones" multiple/);assert.match(text,/data-action="master-update"/);assert.match(text,/data-container-label=/);assert.doesNotMatch(text,/data-master-edit/)});
test('round seven UI exposes fresh export, consumables, tare and container-level cold moves',async()=>{const text=await source();for(const marker of["case'fresh-export'","case'consumables'",'fresh-net-lots','fresh-shipping-boxes','grossWeightKg','tareWeightKg','move-to-cold-storage'])assert.ok(text.includes(marker),marker);assert.doesNotMatch(text,/data-action="move"/);assert.match(text,/active=inv\.filter\(x=>x\.weightKg>0/)});
test('receiving can create and print a basket only before a physical basket scan',async()=>{const text=await source();assert.match(text,/data-print-new-basket>چاپ سبد جدید/);assert.match(text,/printNewBasket\.disabled=!!receivingScan\.value\.trim\(\)/);assert.match(text,/post\('\/api\/containers',\{type:'BASKET'/);assert.match(text,/post\(`\/api\/containers\/\$\{container\.id\}\/label`\)/)});
test('web claims a pending print job before completing it',async()=>{const text=await source(),claim=text.indexOf('print}/claim`'),complete=text.indexOf('print}/${b.dataset.printAction}`');assert.ok(claim>=0&&complete>claim)});
test('wash and slice UI preserve batch identity and treat scale readings as observations',async()=>{const text=await source();assert.match(text,/observedWeightKg/);assert.match(text,/\$\{v\.process\}_OBSERVATION/);assert.match(text,/inputs:\[\{batchId:v\.batchId\}\]/);assert.doesNotMatch(text,/if\(a==='transform'\).*outputWeightKg/)});
test('every sorting output row requires its own hardware-verified container scan',async()=>{const text=await source();assert.match(text,/scanField\('اسکن QR سبد خروجی','outputContainerCode'\)/);assert.match(text,/row\.querySelector\('\[name="outputContainerCode"\]'\)/);assert.match(text,/containerId:target\.id/);assert.match(text,/new Set\(outputs\.map\(x=>x\.containerId\)\)\.size!==outputs\.length/)});
test('customer shipping UI includes Fresh Shipping Boxes in order, assignment and physical scan flows',async()=>{const text=await source();assert.match(text,/FRESH_SHIPPING_BOX/);assert.match(text,/name="shippingBoxIds" multiple/);assert.match(text,/shippingBoxIds=\[\.\.\.f\.elements\.shippingBoxIds\.selectedOptions\]/);assert.match(text,/itemCode:v\.itemCode\.trim\(\)/);assert.doesNotMatch(text,/items:\[\{packageType:'CARTON',quantity:Number\(v\.quantity\)\}\]/)});
test('customer shipping UI prefilters printed packages whose current batches have approved QC',async()=>{const text=await source();assert.match(text,/const latestQcApproved=/);assert.match(text,/function packageBatchIds\(/);assert.match(text,/printed\.has\(x\.id\).*packageBatchIds\(x,packages\)/);assert.match(text,/every\(id=>latestQcApproved\(id,checks\)\)/);assert.match(text,/صلاحیت وضعیت، تخصیص، QC، قفل و چاپ در تمام مراحل دوباره توسط سرور بررسی می‌شود/)});
test('Fresh Export identifies its batch only through a hardware-verified physical basket scan',async()=>{const text=await source(),page=text.slice(text.indexOf("case'fresh-export'"),text.indexOf("case'consumables'"));assert.match(page,/scanField\('اسکن QR سبد Fresh Export','freshContainerCode'\)/);assert.match(text,/scannedContainer\(v\.freshContainerCode,f\.elements\.freshContainerCode\)/);assert.match(text,/containerId:container\.id/);assert.match(text,/eligible\.length!==1/);assert.doesNotMatch(page,/<select name="batchId">/)});
test('Fresh Shipping Box remains visibly pending until the print queue completes its label',async()=>{const text=await source(),page=text.slice(text.indexOf("case'fresh-export'"),text.indexOf("case'consumables'"));assert.match(page,/تا تکمیل موفق چاپ لیبل در وضعیت LABEL_PENDING و غیرقابل ارسال می‌ماند/);assert.match(page,/ساخت جعبه و ایجاد کار چاپ/);assert.match(text,/freshBoxes=.*x\.status==='READY_TO_SHIP'.*printed\.has\(x\.id\)/)});
test('production navigation exposes physical carrier movement, QC checklists, attestation, and device registration',async()=>{const text=await source();for(const endpoint of['qc-checklists','devices'])assert.ok(text.includes(`'${endpoint}'`));for(const action of['container-move','qc-checklist','quality','device'])assert.ok(text.includes(`data-action="${action}"`));assert.match(text,/attestation:\{confirmed:true,role:/);assert.match(text,/\/api\/containers\/\$\{v\.moveContainerId\}\/move/);assert.match(text,/data-retire-device=/)});

test('consumables panel surfaces durable reorder and shortage exceptions',async()=>{const text=await source(),page=text.slice(text.indexOf("case'consumables'"),text.indexOf("case'shipments'"));assert.match(text,/'consumables','exceptions','shipments'/);assert.match(page,/entityType==='CONSUMABLE'/);assert.match(page,/هشدارهای موجودی اقلام/);assert.match(page,/x\.type/);assert.match(page,/x\.severity/)});

test('inventory zone filters come from active reference data and contain no retired cold-room literal',async()=>{const text=await source(),page=text.slice(text.indexOf("case'inventory'"),text.indexOf("case'containers'"));assert.match(page,/d\['master-data\/zones'\]/);assert.match(page,/x\.status==='ACTIVE'/);assert.doesNotMatch(page,/\['RECEIVING','COLD_ROOM'/);assert.match(text,/COLD_ROOM_CLEAN/);assert.match(text,/COLD_ROOM_DIRTY/)});
test('user administration independently regenerates badge PIN',async()=>{const text=await source();assert.match(text,/data-pin=/);assert.match(text,/\/api\/users\/\$\{b\.dataset\.pin\}\/pin/);assert.match(text,/pinAssigned/)});
test('inter-site workflows expose origin controls and require physical destination receipt scans',async()=>{const text=await source(),page=text.slice(text.indexOf("case'transfers'"),text.indexOf("case'tasks'"));for(const action of['internal-create','internal-load','internal-dispatch','transfer'])assert.match(page,new RegExp(`data-action="${action}"`));assert.match(page,/field\('شناسه خودرو','vehicle'/);assert.match(page,/dispatchPackageCodes/);assert.match(page,/receivingContainerCode/);assert.match(page,/data-internal-cancel=/);assert.match(text,/scannedContainer\(v\.receivingContainerCode/);const request=text.match(/post\('\/api\/internal-transfers\/receive',[^;]+/s)?.[0]??'';assert.match(request,/containerId:container\.id/);assert.match(request,/scannedPackageCodes/);assert.match(request,/sessionId:await ensureSession\(\)/);assert.doesNotMatch(request,/receivedBy/)});
test('QC UI only offers checklists to batches at their actual stage and uses split cold-room release zones',async()=>{const text=await source();assert.match(text,/const qcStage=batch=>/);assert.match(text,/x\.product===c\.product&&qcStage\(x\)===c\.stage/);assert.match(text,/COLD_ROOM_CLEAN','COLD_ROOM_DIRTY/);assert.doesNotMatch(text,/\['RECEIVING','SORTING','WASH','SLICE'/)});
