import { submitVerifiedReprint } from './reprint-verification.js';
import { bindScannerInputs } from './scanner-capture.js';
import { browserUuid } from './browser-uuid.js';

const API=localStorage.api||'http://127.0.0.1:3000';
const CLOUD=localStorage.cloudApi||'http://127.0.0.1:4000';
const state={token:sessionStorage.token||'',sessionId:sessionStorage.sessionId||'',route:location.hash.slice(1)||'dashboard',data:{},loading:false};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fa=n=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(Number(n)||0);
const dt=v=>v?new Intl.DateTimeFormat('fa-IR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const key=()=>browserUuid();
const claims=()=>{try{return JSON.parse(atob(state.token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return{}}};
const actor=()=>claims().sub||'web-user';
const deviceId=()=>{let id=localStorage.deviceId;if(!id){id=`WEB-${browserUuid()}`;localStorage.deviceId=id}return id};
const routes=[
 ['dashboard','⌂','داشبورد','نمای کلی عملیات'],
 ['receiving','⇲','دریافت','ثبت ورود و توزین'],
 ['inventory','▦','موجودی','بچ‌ها و جابه‌جایی'],
 ['containers','□','کانتینرها','ظرف‌ها و ظرفیت'],
 ['production','⚙','تولید','فرآوری و افت تولید'],
 ['quality','✓','کنترل کیفیت','قرنطینه و اصلاح'],
 ['packaging','▣','بسته‌بندی','ایجاد بسته'],
 ['shipments','➜','ارسال‌ها','بارگیری و تحویل'],
 ['transfers','⇄','انتقال بین سایت','مانیفست ورودی'],
 ['tasks','☷','کارها','صف وظایف'],
 ['printing','▤','چاپ و لیبل','صف چاپگر'],
 ['trace','⌁','رهگیری','شجره محصول'],
 ['config','⚒','تنظیمات','نسخه و تأیید'],
 ['master-data','◆','داده‌های پایه','محصول، گرید، زون و دوره برداشت'],
 ['users','♙','کاربران و نقش‌ها','دسترسی، مهارت و کارت پرسنلی'],
 ['overrides','!','استثناها','درخواست و تصویب'],
 ['audit','≡','رویدادها','ممیزی و همگام‌سازی'],
 ['cloud','☁','مرکز چندسایتی','وضعیت سایت‌ها'],
 ['system','●','سلامت سامانه','سرویس‌ها و نشست‌ها']
];
const endpoints=['inventory','containers','packages','shipments','tasks','print-jobs','quality-checks','configurations','overrides','audit','outbox','sessions','internal-transfers','inventory-adjustments','deliveries','cycles','master-data/products','master-data/suppliers','master-data/grades','master-data/sizes','master-data/zones','master-data/packageTypes','harvest-periods','users','roles','skills'];

async function request(path,options={}){
  const r=await fetch(API+path,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{}) ,...(options.headers||{})}});
  const j=await r.json();if(!r.ok)throw Error(j.message||j.errorCode||'خطای ارتباط');return j.data??j;
}
const post=(path,body={})=>request(path,{method:'POST',headers:{'Idempotency-Key':key()},body:JSON.stringify(body)});
const remove=path=>request(path,{method:'DELETE',headers:{'Idempotency-Key':key()}});
const can=permission=>{const user=claims();return user.permissions?.includes('*')||user.permissions?.includes(permission)};
async function ensureSession(){if(!state.sessionId){state.sessionId=(await post('/api/sessions',{operatorId:actor(),deviceId:deviceId(),station:'web-console'})).id;sessionStorage.sessionId=state.sessionId}return state.sessionId}
function scannedContainer(code,input){const normalized=String(code||'').trim();if(!normalized||input?.dataset.scanVerified!=='true')throw Error('اسکن سخت‌افزاری ظرف یا سینی الزامی است');const container=(state.data.containers?.items||[]).find(x=>x.code===normalized);if(!container)throw Error('کد اسکن‌شده در فهرست ظروف معتبر نیست');return container}
function toast(message,type='ok'){const el=$('#toast');el.textContent=message;el.className=`show ${type}`;setTimeout(()=>el.className='',3200)}
function status(value){const cls=/APPROVED|ACTIVE|AVAILABLE|COMPLETED|DELIVERED|CONFIRMED|RECEIVED|RELEASED/.test(value)?'good':/FAILED|REJECTED|CANCELLED|WASTED/.test(value)?'bad':/QUARANTINE|PENDING|SUSPENDED/.test(value)?'warn':'neutral';return `<span class="status ${cls}">${esc(value)}</span>`}
function empty(text='هنوز داده‌ای ثبت نشده است'){return `<div class="empty"><b>◇</b><p>${text}</p></div>`}
function table(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:empty()}
function options(items,label='code'){return items.map(x=>`<option value="${esc(x.id)}">${esc(x[label]||x.title||x.id)}</option>`).join('')}
function panel(title,body,extra=''){return `<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${extra}</div></div>${body}</section>`}
function field(label,name,type='text',value='',attrs=''){return `<label><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`}
function scanField(label,name='containerCode'){return `<label><span>${label}</span><input name="${name}" data-scanner-input data-scan-verified="false" readonly inputmode="none" autocomplete="off" required placeholder="برای اسکن لمس کنید"></label>`}
function select(label,name,items){return `<label><span>${label}</span><select name="${name}">${items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label>`}
function referenceSelect(label,name,items){return `<label><span>${label}</span><select name="${name}" required><option value="">انتخاب کنید</option>${items.filter(x=>x.status==='ACTIVE').map(x=>`<option value="${esc(x.code)}">${esc(x.name)}</option>`).join('')}</select></label>`}

function shell(){
 const user=claims();
 return `<div class="app-shell">
 <aside><div class="logo"><span>SM</span><div><b>StoreMesh</b><small>Operations OS</small></div></div>
 <nav>${routes.filter(([id])=>id!=='users'||can('roles:write')).map(([id,icon,title])=>`<a href="#${id}" class="${state.route===id?'active':''}"><i>${icon}</i><span>${title}</span></a>`).join('')}</nav>
 <div class="side-foot"><span class="live-dot"></span><div><b>سایت ایران</b><small>متصل به سرور محلی</small></div></div></aside>
 <main><header><button id="menuButton" class="icon-btn">☰</button><div class="breadcrumbs"><small>STOREMESH / IRAN</small><h1>${esc(routes.find(x=>x[0]===state.route)?.[2]||'داشبورد')}</h1></div>
 <div class="header-actions"><button class="site-switch">IRAN⌄</button><button class="icon-btn" title="اعلان‌ها">●</button><div class="user"><span>${esc((user.username||'U')[0].toUpperCase())}</span><div><b>${esc(user.username||'کاربر')}</b><small>${esc((user.roles||[]).join('، '))}</small></div></div><button id="logout" class="icon-btn" title="خروج">↪</button></div></header>
 <div class="content"><div id="page">${renderPage()}</div></div></main></div>`;
}

function renderPage(){
 const d=state.data,inv=d.inventory?.items||[],containers=d.containers?.items||[],packages=d.packages?.items||[],shipments=d.shipments?.items||[],tasks=d.tasks?.items||[],prints=d['print-jobs']?.items||[];
 if(state.loading)return '<div class="loading"><span></span><p>در حال دریافت اطلاعات عملیات…</p></div>';
 switch(state.route){
 case'dashboard':{
  const total=inv.reduce((n,x)=>n+x.weightKg,0),quarantine=inv.filter(x=>x.zone==='QUARANTINE').length,open=tasks.filter(x=>x.status==='OPEN').length;
  return `<div class="hero"><div><span class="eyebrow">مرکز فرمان عملیات</span><h2>امروز در سایت ایران</h2><p>وضعیت زنده جریان مواد از دریافت تا ارسال</p></div><button data-go="receiving" class="primary">＋ دریافت جدید</button></div>
  <div class="kpis">${[['بچ فعال',inv.length,'▦','green'],['موجودی کل',fa(total)+' kg','◒','blue'],['وظیفه باز',open,'☷','orange'],['قرنطینه',quarantine,'!','red'],['ارسال فعال',shipments.filter(x=>!['DELIVERED','CANCELLED'].includes(x.status)).length,'➜','purple']].map(x=>`<article><span class="kpi-icon ${x[3]}">${x[2]}</span><div><small>${x[0]}</small><b>${x[1]}</b></div></article>`).join('')}</div>
  <div class="two-col">${panel('توزیع موجودی در زون‌ها',zoneChart(inv))}${panel('کارهای اولویت‌دار',taskCards(tasks.slice(0,5)))}</div>
  <div class="two-col">${panel('آخرین بچ‌ها',inventoryTable(inv.slice(-6).reverse()))}${panel('وضعیت چاپ و لیبل',printCards(prints.slice(-5).reverse()))}</div>`;
 }
 case'receiving':{const deliveries=d.deliveries?.items||[],open=deliveries.find(x=>x.status==='OPEN'&&x.sessionId===state.sessionId),products=d['master-data/products']?.items||[],suppliers=d['master-data/suppliers']?.items||[],grades=d['master-data/grades']?.items||[],sizes=d['master-data/sizes']?.items||[],basketRows=open?.baskets?.map((x,i)=>{const b=inv.find(y=>y.id===x.batchId);return`<tr><td>${i+1}</td><td>${esc(b?.code)}</td><td>${esc(containers.find(c=>c.id===x.containerId)?.code)}</td><td>${fa(x.weightKg)} kg</td><td>${dt(x.receivedAt)}</td></tr>`})||[];return `<div class="page-intro"><div><h2>دریافت چندسبدی</h2><p>یک تحویل، چند سبد توزین‌شده و یک بچ تجمیعی</p></div><span class="device-chip">${open?'● تحویل باز':'○ آماده شروع'}</span></div>
  ${!open?panel('۱. شروع تحویل',`<form data-action="start-delivery" class="inline-form">${referenceSelect('تأمین‌کننده','supplierCode',suppliers)}<button class="primary">شروع تحویل</button></form>`):panel(`۲. توزین سبدها — ${esc(open.code)}`,`<form data-action="receive" data-delivery="${open.id}" data-supplier="${open.supplierCode}" class="form-grid">${scanField('اسکن سخت‌افزاری QR سبد')}${referenceSelect('محصول','product',products)}${referenceSelect('گرید','grade',grades)}${referenceSelect('اندازه','size',sizes)}${field('وزن خالص (kg)','weightKg','number','','step=".001" min=".001" required')}<button class="primary">ثبت سبد و ادامه</button></form><p class="muted">دوره برداشت از تاریخ دریافت و تنظیمات مدیر به‌صورت خودکار تعیین می‌شود. برچسب دائمی ظرف دوباره چاپ نمی‌شود.</p>`)}
  ${open?panel(`سبدهای تحویل (${basketRows.length})`,`${table(['ردیف','بچ سبد','ظرف','وزن','زمان'],basketRows)}<button class="primary" data-finish-delivery="${open.id}" ${basketRows.length?'':'disabled'}>پایان تحویل و ساخت بچ تجمیعی</button>`):''}
  ${panel('تحویل‌های اخیر',table(['کد','تأمین‌کننده','سبدها','وضعیت','زمان'],deliveries.slice(-8).reverse().map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.supplierCode)}</td><td>${x.baskets?.length||0}</td><td>${status(x.status)}</td><td>${dt(x.startedAt)}</td></tr>`)))}`;}
 case'inventory':return `<div class="toolbar"><div class="search">⌕ <input id="inventorySearch" placeholder="جست‌وجوی کد، محصول، گرید یا زون"></div><button data-export="inventory">دریافت CSV</button><button data-go="receiving" class="primary">＋ بچ جدید</button></div>
  <div class="filters"><button class="active">همه ${inv.length}</button>${['RECEIVING','COLD_ROOM','SORTING','PROCESSING','PACKAGING','QUARANTINE'].map(z=>`<button data-zone="${z}">${z} ${inv.filter(x=>x.zone===z).length}</button>`).join('')}</div>
  ${panel('موجودی لحظه‌ای',`<div id="inventoryTable">${inventoryTable(inv)}</div>`)}
  <div class="two-col">${panel('انتقال بچ بین زون‌ها',`<form data-action="move" class="stack-form"><label><span>بچ</span><select name="batchId">${options(inv)}</select></label>${select('زون مقصد','zone',['COLD_ROOM','SORTING','WASHING','SLICING','FREEZING','PROCESSING','PACKAGING','SHIPPING','QUARANTINE'])}<button class="primary">ثبت جابه‌جایی</button></form>`)}
  ${panel('تعویض ظرف فیزیکی بچ',`<form data-action="assign-container" class="stack-form"><label><span>بچ</span><select name="batchId">${options(inv)}</select></label>${scanField('اسکن QR ظرف مقصد','destinationContainerCode')}<button class="primary">انتقال به ظرف اسکن‌شده</button></form>`)}</div>`;
 case'containers':return `<div class="split-head"><div><h2>مدیریت کانتینرها</h2><p>کنترل ظرفیت، محصول یکتا و جابه‌جایی گروهی</p></div></div>
  ${panel('ایجاد کانتینر',`<form data-action="container" class="stack-form">${select('نوع','type',['BASKET','CRATE','TRAY'])}${field('ظرفیت kg','capacityKg','number','100','min="1"')}${select('زون اولیه','zone',['RECEIVING','COLD_ROOM','SORTING','PROCESSING'])}${select('زون مجاز تعیین‌شده','designatedZone',['RECEIVING','COLD_ROOM','SORTING','PROCESSING'])}<button class="primary">ایجاد و چاپ کد</button></form>`)}
  <div class="container-grid">${containers.length?containers.map(c=>`<article class="container-card"><div><span class="box-icon">□</span>${status(c.status)}</div><h3>${esc(c.code)}</h3><p>${esc(c.type)} · ${esc(c.zone)}</p><div class="meter"><span style="width:${Math.min(100,(c.batchIds?.reduce((n,id)=>n+(inv.find(x=>x.id===id)?.weightKg||0),0)/c.capacityKg)*100)}%"></span></div><small>${c.batchIds?.length||0} بچ از ظرفیت ${fa(c.capacityKg)} kg</small></article>`).join(''):empty()}</div>`;
 case'production':{const grades=d['master-data/grades']?.items||[],sizes=d['master-data/sizes']?.items||[],cycles=d.cycles?.items||[],machineConfig=(d.configurations?.items||[]).find(x=>x.scope==='STATION_MACHINES'&&x.status==='ACTIVE')?.values||{},cycleRows=cycles.slice().reverse().map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${esc(c.type)}</td><td>${esc(c.machineId)}</td><td>${esc((c.batchIds||[]).map(id=>inv.find(x=>x.id===id)?.code).filter(Boolean).join('، '))}</td><td>${status(c.status)}</td><td class="actions">${cycleActions(c)}</td></tr>`);return `<div class="two-col">${panel('اجرای شست‌وشو / اسلایس',`<form data-action="transform" class="stack-form"><label><span>بچ ورودی</span><select name="batchId">${options(inv.filter(x=>x.weightKg>0&&!x.isAggregate))}</select></label>${scanField('اسکن QR ظرف')}${select('فرآیند','process',['WASH','SLICE'])}${field('وزن مصرفی kg','consumeWeightKg','number','10','step=".001"')}${field('وزن خروجی kg','outputWeightKg','number','9.2','step=".001"')}<div class="form-row">${field('محصول خروجی','product','','Truffle')}${referenceSelect('گرید','grade',grades)}</div><button class="primary">ثبت فرآوری و شجره</button></form>`)}
  ${panel('تفکیک چندخروجی',`<form data-action="sorting" class="stack-form"><label><span>بچ ورودی</span><select name="batchId">${options(inv.filter(x=>x.weightKg>0&&!x.isAggregate))}</select></label>${scanField('اسکن QR سبد')}<div data-sort-outputs><div class="sort-output-row">${referenceSelect('گرید','outputGrade',grades)}${referenceSelect('اندازه','outputSize',sizes)}${field('وزن kg','outputWeight','number','','step=".001" min=".001" required')}<button type="button" data-remove-output>×</button></div></div><button type="button" data-add-output>＋ خروجی دیگر</button><button class="primary">اجرای Sorting</button></form>`)}</div>
  <div class="two-col">${panel('ساخت چرخه ماشین',`<form data-action="cycle" class="stack-form">${select('فرآیند','type',['FREEZE','FREEZE_DRY','DRY'])}${scanField('اسکن سینی / سبد','cycleContainerCode')}<p class="muted">شناسه ماشین از تنظیم فعال مدیر خوانده می‌شود؛ ورود دستی ممکن نیست.</p><button class="primary" ${Object.keys(machineConfig).length?'':'disabled'}>ایجاد چرخه آماده</button></form>`)}${panel('وضعیت زنده',`<div class="cycle-live">${['FREEZE','FREEZE_DRY','DRY'].map(type=>{const c=cycles.find(x=>x.type===type&&!['COMPLETED','FAILED','CANCELLED'].includes(x.status));return`<article><b>${type}</b>${c?`${status(c.status)}<small>از ${dt(c.startedAt||c.createdAt)} · ${esc(c.operatorId)}</small>`:'<span class="status neutral">IDLE</span>'}</article>`}).join('')}</div>`)}</div>
  ${panel('چرخه‌های تولید',table(['کد','فرآیند','ماشین ثابت','بچ‌ها','وضعیت','عملیات'],cycleRows))}
  ${panel('بچ‌های فرآوری‌شده',inventoryTable(inv.filter(x=>x.process||/WASH|SLIC|FROZEN|DRIED|SORTED|MERGED/.test(x.status))))}`;
 }
 case'quality':{const checks=d['quality-checks']?.items||[],quarantined=inv.filter(x=>x.zone==='QUARANTINE');return `<div class="kpis compact"><article><span class="kpi-icon green">✓</span><div><small>تأیید شده</small><b>${checks.filter(x=>x.result==='APPROVED').length}</b></div></article><article><span class="kpi-icon orange">!</span><div><small>قرنطینه</small><b>${quarantined.length}</b></div></article><article><span class="kpi-icon red">×</span><div><small>رد شده</small><b>${checks.filter(x=>x.result==='REJECTED').length}</b></div></article></div>
  <div class="two-col">${panel('ثبت نتیجه بازرسی',`<form data-action="quality" class="stack-form"><label><span>بچ</span><select name="batchId">${options(inv)}</select></label>${select('نتیجه','result',['APPROVED','QUARANTINED','REJECTED'])}${field('توضیحات','notes','','بازرسی ظاهری و دمایی')}<button class="primary">ثبت نتیجه QC</button></form>`)}
  ${panel('آزادسازی قرنطینه',quarantined.length?`<form data-action="release" class="stack-form"><label><span>بچ قرنطینه</span><select name="batchId">${options(quarantined)}</select></label>${field('دلیل آزادسازی','reason','','تأیید آزمایش تکمیلی')}${select('زون مقصد','destinationZone',['COLD_ROOM','PROCESSING','PACKAGING'])}<button class="primary">آزادسازی با تأیید</button></form>`:empty('بچ قرنطینه‌ای وجود ندارد'))}</div>
  ${panel('سوابق کنترل کیفیت',table(['بچ','نتیجه','بازرس','توضیح','زمان'],checks.slice().reverse().map(q=>`<tr><td>${esc(inv.find(x=>x.id===q.batchId)?.code)}</td><td>${status(q.result)}</td><td>${esc(q.inspectorId)}</td><td>${esc(q.notes)}</td><td>${dt(q.createdAt)}</td></tr>`)))}`;}
 case'packaging':return `<div class="two-col">${panel('ایجاد بسته',`<form data-action="package" class="stack-form">${select('سطح بسته','level',['CARTON','EPS','PALLET'])}${select('نوع بسته','type',['CARTON','EPS','PALLET','BAG','JAR'])}<label><span>بچ موجود (برای کارتن)</span><select name="batchId"><option value="">—</option>${options(inv.filter(x=>x.weightKg>0))}</select></label><label><span>بسته فرزند (برای EPS/پالت)</span><select name="childPackageId"><option value="">—</option>${options(packages.filter(x=>x.status==='READY_TO_SHIP'&&!x.parentPackageId))}</select></label>${field('وزن بسته kg','weightKg','number','2','step=".001"')}<button class="primary">ایجاد بسته</button></form>`)}
  ${panel('خلاصه بسته‌بندی',`<div class="big-stat"><b>${packages.length}</b><span>بسته ایجادشده</span></div><div class="big-stat"><b>${fa(packages.reduce((n,p)=>n+(p.items||[]).reduce((s,x)=>s+x.weightKg,0),0))}</b><span>کیلوگرم بسته‌بندی</span></div>`)}</div>
  ${panel('فهرست بسته‌ها',table(['کد','سطح','محتوا','وزن','وضعیت','عملیات'],packages.map(p=>`<tr><td><b>${esc(p.code)}</b></td><td>${esc(p.level||p.type)}</td><td>${p.items?.length||p.childPackageIds?.length||0}</td><td>${fa((p.items||[]).reduce((n,x)=>n+x.weightKg,0))} kg</td><td>${status(p.status)}</td><td class="actions">${packageAction(p)}</td></tr>`)))}`;
 case'shipments':return `<div class="two-col">${panel('ایجاد محموله',`<form data-action="shipment" class="stack-form">${select('سایت مقصد','destinationSite',['DUBAI','ROME','IRAN'])}<label><span>بسته‌های آماده</span><select name="packageId">${options(packages.filter(x=>x.status==='READY_TO_SHIP'&&!x.shipmentId&&!x.parentPackageId))}</select></label><button class="primary">ایجاد Shipment</button></form>`)}${panel('چرخه ارسال','<div class="timeline"><span class="done">READY</span><i></i><span>LOADED</span><i></i><span>DISPATCHED</span><i></i><span>DELIVERED</span></div>')}</div>
  ${panel('محموله‌ها',table(['کد','مقصد','بسته‌ها','وضعیت','عملیات'],shipments.map(s=>`<tr><td><b>${esc(s.code)}</b></td><td>${esc(s.destinationSite)}</td><td>${s.packageIds?.length||0}</td><td>${status(s.status)}</td><td class="actions">${shipmentActions(s)}</td></tr>`)))}`;
 case'transfers':{const transfers=d['internal-transfers']?.items||[];return `<div class="two-col">${panel('دریافت مانیفست سایت دیگر',`<form data-action="transfer" class="stack-form"><label><span>JSON مانیفست</span><textarea name="manifest" rows="10" placeholder='{"sourceSite":"IRAN",...}'></textarea></label><button class="primary">اعتبارسنجی و دریافت</button></form>`)}${panel('قواعد انتقال',`<ul class="rules"><li>هر سایت دیتابیس مستقل دارد</li><li>فقط مانیفست DISPATCHED پذیرفته می‌شود</li><li>دریافت تکراری مسدود می‌شود</li><li>منبع خارجی در شجره حفظ می‌شود</li></ul>`)}</div>
  ${panel('انتقال‌های دریافت‌شده',table(['سایت مبدأ','Shipment','بچ‌های ایجادشده','دریافت‌کننده','زمان'],transfers.map(x=>`<tr><td>${esc(x.sourceSite)}</td><td>${esc(x.shipmentCode)}</td><td>${x.batchIds?.length||0}</td><td>${esc(x.receivedBy)}</td><td>${dt(x.receivedAt)}</td></tr>`)))}`;}
 case'tasks':return `<div class="two-col">${panel('ایجاد وظیفه',`<form data-action="task" class="stack-form">${field('عنوان کار','title','','تفکیک سفارش جدید')}${select('زون','zone',['RECEIVING','SORTING','WASHING','PACKAGING','SHIPPING'])}${field('اولویت','priority','number','50','min="1" max="100"')}<button class="primary">افزودن به صف</button></form>`)}${panel('نمای صف',`<div class="task-summary"><div><b>${tasks.filter(x=>x.status==='OPEN').length}</b><span>باز</span></div><div><b>${tasks.filter(x=>x.status==='IN_PROGRESS').length}</b><span>در حال انجام</span></div></div>`)}</div>${panel('وظایف عملیات',taskCards(tasks))}`;
 case'printing':return `<div class="printer-head"><div><span class="printer-icon">▤</span><div><h2>Zebra ZT411</h2><p>چاپگر اصلی سایت · 300 dpi</p></div></div><span class="device-chip">● متصل</span></div>${panel('صف چاپ',printCards(prints))}`;
 case'trace':return `<div class="trace-search"><h2>رهگیری کامل محصول</h2><p>کد بچ را وارد کنید تا منشأ، فرآیندها، اندازه‌گیری‌ها و جابه‌جایی‌ها نمایش داده شود.</p><form data-action="trace"><input name="code" placeholder="B-IRAN-000001"><button class="primary">نمایش شجره</button></form></div><div id="traceResult">${empty('برای شروع یک کد Batch جست‌وجو کنید')}</div>`;
 case'master-data':{const editable=can('master-data:write'),types=[['products','محصولات'],['suppliers','تأمین‌کنندگان'],['grades','گریدها'],['sizes','اندازه‌ها'],['zones','زون‌ها'],['packageTypes','انواع بسته']];return `<div class="page-intro"><div><h2>مدیریت داده‌های پایه</h2><p>کدها حذف نمی‌شوند؛ فقط فعال یا غیرفعال می‌شوند.</p></div>${editable?'<span class="device-chip">● دسترسی ویرایش</span>':'<span class="device-chip">فقط مشاهده</span>'}</div>${editable?panel('رکورد پایه جدید',`<form data-action="master-create" class="inline-form">${select('دسته','type',types.map(x=>x[0]))}${field('کد','code','','NEW_CODE','required pattern="[A-Za-z0-9_-]+"')}${field('نام','name','','عنوان قابل نمایش','required')}<button class="primary">ایجاد</button></form>`):''}<div class="two-col">${types.map(([type,title])=>panel(title,masterDataTable(type,d[`master-data/${type}`]?.items||[],editable))).join('')}</div>${panel('دوره‌های برداشت',`${editable?`<form data-action="harvest-create" class="form-grid">${field('کد','code','','HARVEST_2026','required')}${field('عنوان','label','','برداشت ۱۴۰۵','required')}${field('از تاریخ','startDate','date','','required')}${field('تا تاریخ','endDate','date','','required')}<button class="primary">افزودن دوره</button></form>`:''}${table(['کد','عنوان','بازه','وضعیت','عملیات'],(d['harvest-periods']?.items||[]).map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.label)}</td><td>${esc(x.startDate)} ← ${esc(x.endDate)}</td><td>${status(x.status)}</td><td class="actions">${editable?`<button data-harvest-edit="${x.id}">ویرایش</button><button data-harvest="${x.id}" data-status="${x.status==='ACTIVE'?'INACTIVE':'ACTIVE'}">${x.status==='ACTIVE'?'غیرفعال‌کردن':'فعال‌کردن'}</button>`:'—'}</td></tr>`))}`)}`;}
 case'users':{if(!can('roles:write'))return empty('دسترسی مدیریت کاربران فقط برای مدیر سامانه است');const users=d.users?.items||[],roles=d.roles?.items||[],skills=d.skills?.items||[],permissions=[...new Set(roles.flatMap(x=>x.permissions||[]).filter(x=>x!=='*'))].sort();return `<div class="page-intro"><div><h2>کاربران، نقش‌ها و مهارت‌ها</h2><p>تغییر دسترسی بلافاصله روی ورود بعدی اثر می‌گذارد.</p></div><span class="device-chip">ADMIN</span></div><div class="two-col">${panel('تخصیص نقش',`<form data-action="user-role" class="stack-form"><label><span>کاربر</span><select name="userId">${options(users,'username')}</select></label><label><span>نقش</span><select name="roleCode">${roles.map(x=>`<option value="${esc(x.code)}">${esc(x.name)} (${esc(x.code)})</option>`).join('')}</select></label><button class="primary">تخصیص نقش</button></form>`)}${panel('تخصیص مهارت',`<form data-action="user-skill" class="stack-form"><label><span>کاربر</span><select name="userId">${options(users,'username')}</select></label><label><span>مهارت</span><select name="skillId">${options(skills,'name')}</select></label><button class="primary" ${skills.length?'':'disabled'}>تخصیص مهارت</button></form><form data-action="skill-create" class="inline-form">${field('کد مهارت','code','','WEIGHING')}${field('نام مهارت','name','','توزین دقیق')}<button>مهارت جدید</button></form>`)}</div>${panel('نقش سفارشی جدید',`<form data-action="role-create" class="stack-form">${field('کد نقش','code','','CUSTOM_ROLE','required')}${field('نام نقش','name','','نقش سفارشی','required')}<div class="permission-grid">${permissions.map(p=>`<label><input type="checkbox" name="permissions" value="${esc(p)}"> ${esc(p)}</label>`).join('')}</div><button class="primary">ایجاد نقش</button></form>`)}${panel('فهرست کاربران',table(['کاربر','وضعیت','نقش‌ها','مهارت‌ها','کارت پرسنلی'],users.map(u=>`<tr><td><b>${esc(u.username)}</b><small class="mono">${esc(u.id)}</small></td><td>${status(u.status)}</td><td>${(u.roles||[]).map(code=>`<span class="assignment-chip">${esc(code)} <button data-revoke-role="${esc(code)}" data-user="${u.id}">×</button></span>`).join('')||'—'}</td><td>${(u.skills||[]).map(id=>`<span class="assignment-chip">${esc(skills.find(x=>x.id===id)?.name||id)} <button data-revoke-skill="${id}" data-user="${u.id}">×</button></span>`).join('')||'—'}</td><td><button data-badge="${u.id}">${u.badgeAssigned?'بازسازی و ابطال قبلی':'صدور Badge'}</button></td></tr>`)))}`;}
 case'config':{const configs=d.configurations?.items||[];return `<div class="two-col">${panel('نسخه تنظیمات جدید',`<form data-action="config" class="stack-form">${field('دامنه','scope','','SITE_OPERATION')}${field('مقادیر JSON','values','','{&quot;maxLossPercent&quot;: 15}')}<button class="primary">ایجاد Draft</button></form>`)}${panel('چرخه چهارچشمی','<div class="approval-flow"><span>DRAFT</span><b>←</b><span>APPROVED</span><b>←</b><span>ACTIVE</span></div><p class="muted">سازنده اجازه تأیید نسخه خودش را ندارد.</p>')}</div>${panel('نسخه‌ها',table(['دامنه','نسخه','وضعیت','سازنده','عملیات'],configs.map(c=>`<tr><td>${esc(c.scope)}</td><td>v${c.sequence}</td><td>${status(c.status)}</td><td>${esc(c.createdBy)}</td><td class="actions">${c.status==='DRAFT'? `<button data-config="${c.id}" data-transition="approve">تأیید</button>`:c.status==='APPROVED'? `<button data-config="${c.id}" data-transition="activate">فعال‌سازی</button>`:'—'}</td></tr>`)))}`;}
 case'overrides':{const items=d.overrides?.items||[];return `<div class="two-col">${panel('درخواست استثنا',`<form data-action="override" class="stack-form">${field('کد قانون','ruleCode','','CAPACITY_LIMIT')}${field('شناسه موجودیت','entityId','','manual')}${field('دلیل','reason','','شرایط اضطراری مستندشده')}<button class="primary">ارسال برای تأیید</button></form>`)}${panel('اصل کنترل داخلی','<div class="shield">◆</div><h3>تفکیک وظایف</h3><p class="muted">درخواست‌کننده نمی‌تواند استثنای خودش را تصویب کند.</p>')}</div>${panel('درخواست‌ها',table(['قانون','دلیل','درخواست‌کننده','وضعیت','عملیات'],items.map(o=>`<tr><td>${esc(o.ruleCode)}</td><td>${esc(o.reason)}</td><td>${esc(o.requestedBy)}</td><td>${status(o.status)}</td><td class="actions">${o.status==='PENDING'? `<button data-override="${o.id}" data-decision="APPROVED">تأیید</button><button class="danger-link" data-override="${o.id}" data-decision="REJECTED">رد</button>`:'—'}</td></tr>`)))}`;}
 case'audit':{const audit=d.audit?.items||[],outbox=d.outbox?.items||[];return `<div class="kpis compact"><article><span class="kpi-icon blue">≡</span><div><small>کل رویدادها</small><b>${audit.length}</b></div></article><article><span class="kpi-icon orange">↻</span><div><small>در انتظار Cloud</small><b>${outbox.filter(x=>x.status==='PENDING').length}</b></div></article></div>${panel('دفتر رویداد تغییرناپذیر',table(['نوع رویداد','موجودیت','سایت','زمان'],audit.slice().reverse().map(e=>`<tr><td><b>${esc(e.type)}</b></td><td class="mono">${esc(e.entityId)}</td><td>${esc(e.site)}</td><td>${dt(e.occurredAt)}</td></tr>`)))}`;}
 case'cloud':return `<div id="cloudContent"><div class="loading small"><span></span><p>دریافت وضعیت سایت‌ها…</p></div></div>`;
 case'system':{const sessions=d.sessions?.items||[];return `<div class="service-grid"><article><span class="service-ok">●</span><h3>Site API</h3><p>IRAN · Port 3000</p><b>Operational</b></article><article><span class="service-ok">●</span><h3>PostgreSQL</h3><p>پایگاه داده مستقل سایت</p><b>Ready</b></article><article><span class="service-ok">●</span><h3>Cloud Sync</h3><p>Outbox Publisher</p><b>Connected</b></article><article><span class="service-ok">●</span><h3>Web Console</h3><p>نسخه کامل UI</p><b>Online</b></article></div>${panel('نشست‌های عملیاتی',table(['اپراتور','ایستگاه','وضعیت','شروع','عملیات'],sessions.slice().reverse().map(s=>`<tr><td>${esc(s.operatorId)}</td><td>${esc(s.station)}</td><td>${status(s.status)}</td><td>${dt(s.startedAt)}</td><td class="actions">${s.status==='ACTIVE'? `<button data-session="${s.id}" data-session-action="suspend">تعلیق</button><button data-session="${s.id}" data-session-action="complete">پایان</button>`:s.status==='SUSPENDED'? `<button data-session="${s.id}" data-session-action="resume">ادامه</button>`:'—'}</td></tr>`)))}`;}
 default:return empty('صفحه پیدا نشد');
 }}

function inventoryTable(items){return table(['کد بچ','محصول','گرید/اندازه','وزن','زون','وضعیت'],items.map(x=>`<tr><td><b class="mono">${esc(x.code)}</b></td><td>${esc(x.product)}</td><td>${esc(x.grade)} · ${esc(x.size)}</td><td><b>${fa(x.weightKg)}</b> kg</td><td>${esc(x.zone)}</td><td>${status(x.status)}</td></tr>`))}
function masterDataTable(type,items,editable){return table(['کد','نام','وضعیت','عملیات'],items.map(x=>`<tr><td><b>${esc(x.code)}</b></td><td>${esc(x.name)}</td><td>${status(x.status)}</td><td class="actions">${editable?`<button data-master-edit="${x.id}" data-master-type="${type}" data-master-name="${esc(x.name)}">ویرایش نام</button><button data-master-type="${type}" data-master-id="${x.id}" data-status="${x.status==='ACTIVE'?'INACTIVE':'ACTIVE'}">${x.status==='ACTIVE'?'غیرفعال‌کردن':'فعال‌کردن'}</button>`:'—'}</td></tr>`))}
function taskCards(items){return items.length?`<div class="task-list">${items.map(t=>`<article><span class="priority p${Math.ceil((t.priority||50)/25)}">${t.priority||50}</span><div><b>${esc(t.title)}</b><small>${esc(t.zone)} · ${dt(t.createdAt)}</small></div>${status(t.status)}${t.status==='OPEN'?`<button data-task="${t.id}">شروع</button>`:''}</article>`).join('')}</div>`:empty('کاری در صف نیست')}
function printCards(items){return items.length?`<div class="print-list">${items.map(j=>`<article><span class="label-icon">▤</span><div><b>${esc(j.label)}</b><small>${esc(j.entityType)} · تلاش ${j.attempts||0}</small></div>${status(j.status)}<div class="actions">${j.status==='PENDING'?`<button data-print="${j.id}" data-print-action="complete">چاپ شد</button><button data-print="${j.id}" data-print-action="fail">خطا</button>`:j.status==='FAILED'?`<label class="reprint-scan"><span>اسکن لیبل موجود</span><input data-reprint-scan data-scanner-input data-scan-verified="false" readonly inputmode="none" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="اسکنر را روی لیبل بگیرید"></label><button data-print="${j.id}" data-print-action="retry">تأیید اسکن و چاپ مجدد</button>`:''}</div></article>`).join('')}</div>`:empty('صف چاپ خالی است')}
function zoneChart(inv){const groups=Object.entries(inv.reduce((a,x)=>(a[x.zone]=(a[x.zone]||0)+x.weightKg,a),{})).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...groups.map(x=>x[1]));return groups.length?`<div class="bar-chart">${groups.map(([z,n])=>`<div><span>${esc(z)}</span><i><b style="width:${n/max*100}%"></b></i><strong>${fa(n)} kg</strong></div>`).join('')}</div>`:empty()}
function shipmentActions(s){const next={READY:'load',LOADED:'dispatch',DISPATCHED:'deliver'}[s.status];return next?`<button data-shipment="${s.id}" data-shipment-action="${next}">${{load:'بارگیری',dispatch:'ارسال',deliver:'تحویل'}[next]}</button>`:'—'}
function packageAction(p){const next={DRAFT:'pack',PACKING:'seal',READY_FOR_LABEL:'print',PRINTING:'print_success',LABEL_PENDING:'retry',LABEL_PRINTED:'ready'}[p.status];return next?`<button data-package="${p.id}" data-package-action="${next}">${{pack:'شروع',seal:'پلمب',print:'چاپ',print_success:'تأیید چاپ',retry:'تلاش مجدد',ready:'آماده ارسال'}[next]}</button>`:'—'}
function cycleActions(c){const actions={READY:['start','cancel'],RUNNING:['pause','complete'],IN_PROGRESS:['pause','complete'],PAUSED:['resume','cancel'],COMPLETING:['finish']}[c.status]||[];return actions.map(action=>`<button data-cycle="${c.id}" data-cycle-action="${action}">${{start:'شروع',pause:'مکث',resume:'ادامه',complete:'پایان بارگیری',finish:'ثبت وزن و تخلیه',cancel:'لغو'}[action]}</button>`).join('')||'—'}

async function loadData(){
 state.loading=true;render();
 try{const results=await Promise.all(endpoints.map(async e=>[e,await request('/api/'+e).catch(()=>({items:[]}))]));state.data=Object.fromEntries(results)}
 catch(e){toast(e.message,'bad')}finally{state.loading=false;render();if(state.route==='cloud')loadCloud()}
}
function render(){if(!state.token){$('#loginDialog').showModal();return}$('#app').innerHTML=shell();bindShell();bindScannerInputs($('#app'))}
function bindShell(){
 $('#logout')?.addEventListener('click',()=>{sessionStorage.clear();state.token='';state.sessionId='';location.reload()});
 $('#menuButton')?.addEventListener('click',()=>document.querySelector('aside').classList.toggle('open'));
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);
 document.querySelectorAll('form[data-action]').forEach(f=>f.onsubmit=handleForm);
 $('#inventorySearch')?.addEventListener('input',e=>{$('#inventoryTable').innerHTML=inventoryTable((state.data.inventory?.items||[]).filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(e.target.value.toLowerCase()))))});
 document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{$('#inventoryTable').innerHTML=inventoryTable((state.data.inventory?.items||[]).filter(x=>x.zone===b.dataset.zone));document.querySelectorAll('[data-zone]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
 document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>act(()=>post(`/api/tasks/${b.dataset.task}/claim`,{operatorId:actor()}),'وظیفه به شما تخصیص یافت'));
 document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>act(async()=>{
  const sessionId=await ensureSession();let body=JSON.stringify({sessionId});
  if(b.dataset.printAction==='fail')body=JSON.stringify({reason:'خطای چاپگر',sessionId});
  if(b.dataset.printAction==='retry'){
   const job=(state.data['print-jobs']?.items||[]).find(j=>String(j.id)===b.dataset.print);
   const scanned=b.closest('article')?.querySelector('[data-reprint-scan]')?.value;
   return submitVerifiedReprint({jobId:b.dataset.print,scannedValue:scanned,expectedIdentity:job?.label,sessionId,send:request});
  }
  return request(`/api/print-jobs/${b.dataset.print}/${b.dataset.printAction}`,{method:'POST',body});
 }, 'وضعیت چاپ به‌روزرسانی شد'));
 document.querySelectorAll('[data-shipment]').forEach(b=>b.onclick=()=>act(()=>post(`/api/shipments/${b.dataset.shipment}/${b.dataset.shipmentAction}`),'وضعیت محموله تغییر کرد'));
 document.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>act(()=>post(`/api/packages/${b.dataset.package}/${b.dataset.packageAction}`),'وضعیت بسته تغییر کرد'));
 document.querySelectorAll('[data-cycle]').forEach(b=>b.onclick=()=>act(async()=>{const cycle=(state.data.cycles?.items||[]).find(x=>x.id===b.dataset.cycle),action=b.dataset.cycleAction,body={sessionId:await ensureSession()};if(action==='finish'&&cycle.type!=='FREEZE'){body.finalWeights={};for(const batchId of cycle.batchIds){const batch=(state.data.inventory?.items||[]).find(x=>x.id===batchId),value=prompt(`وزن نهایی ${batch?.code||batchId} (kg)`);if(!(Number(value)>0))throw Error('وزن نهایی معتبر برای همه بچ‌ها الزامی است');body.finalWeights[batchId]=Number(value)}}return post(`/api/cycles/${cycle.id}/${action}`,body)},'وضعیت چرخه به‌روزرسانی شد'));
 document.querySelectorAll('[data-master-id]').forEach(b=>b.onclick=()=>act(()=>post(`/api/master-data/${b.dataset.masterType}/${b.dataset.masterId}/update`,{status:b.dataset.status}),'وضعیت داده پایه تغییر کرد'));
 document.querySelectorAll('[data-master-edit]').forEach(b=>b.onclick=()=>{const name=prompt('نام جدید:',b.dataset.masterName);if(name?.trim())act(()=>post(`/api/master-data/${b.dataset.masterType}/${b.dataset.masterEdit}/update`,{name:name.trim()}),'نام داده پایه ویرایش شد')});
 document.querySelectorAll('[data-harvest]').forEach(b=>b.onclick=()=>act(()=>post(`/api/harvest-periods/${b.dataset.harvest}/update`,{status:b.dataset.status}),'وضعیت دوره برداشت تغییر کرد'));
 document.querySelectorAll('[data-harvest-edit]').forEach(b=>b.onclick=()=>{const item=(state.data['harvest-periods']?.items||[]).find(x=>x.id===b.dataset.harvestEdit),label=prompt('عنوان دوره:',item.label);if(label===null)return;const startDate=prompt('تاریخ شروع YYYY-MM-DD:',item.startDate);if(startDate===null)return;const endDate=prompt('تاریخ پایان YYYY-MM-DD:',item.endDate);if(endDate===null)return;act(()=>post(`/api/harvest-periods/${item.id}/update`,{label,startDate,endDate}),'دوره برداشت ویرایش شد')});
 document.querySelectorAll('[data-revoke-role]').forEach(b=>b.onclick=()=>act(()=>remove(`/api/users/${b.dataset.user}/roles/${encodeURIComponent(b.dataset.revokeRole)}`),'نقش کاربر لغو شد'));
 document.querySelectorAll('[data-revoke-skill]').forEach(b=>b.onclick=()=>act(()=>remove(`/api/users/${b.dataset.user}/skills/${b.dataset.revokeSkill}`),'مهارت کاربر لغو شد'));
 document.querySelectorAll('[data-badge]').forEach(b=>b.onclick=async()=>{try{const result=await post(`/api/users/${b.dataset.badge}/badge`);prompt('کد Badge فقط همین یک بار نمایش داده می‌شود؛ آن را چاپ یا کپی کنید:',result.badgeCode);await loadData()}catch(e){toast(e.message,'bad')}});
 document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>act(()=>post(`/api/sessions/${b.dataset.session}/${b.dataset.sessionAction}`),'نشست به‌روزرسانی شد'));
 document.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>act(()=>post(`/api/configurations/${b.dataset.config}/${b.dataset.transition}`,{userId:actor()==='admin-1'?'approver-2':actor()}),'نسخه تنظیمات به‌روزرسانی شد'));
 document.querySelectorAll('[data-override]').forEach(b=>b.onclick=()=>act(()=>post(`/api/overrides/${b.dataset.override}/resolve`,{decision:b.dataset.decision,resolvedBy:actor()==='admin-1'?'approver-2':actor(),note:'بررسی در کنسول وب'}),'درخواست تعیین تکلیف شد'));
 document.querySelector('[data-finish-delivery]')?.addEventListener('click',e=>act(()=>post(`/api/deliveries/${e.currentTarget.dataset.finishDelivery}/complete`,{sessionId:state.sessionId}),'تحویل تکمیل و تسک سردخانه ایجاد شد'));
 document.querySelector('[data-add-output]')?.addEventListener('click',()=>{const host=document.querySelector('[data-sort-outputs]'),row=host.querySelector('.sort-output-row').cloneNode(true);row.querySelectorAll('input').forEach(x=>x.value='');row.querySelectorAll('select').forEach(x=>x.selectedIndex=0);host.append(row);bindSortRemovers()});bindSortRemovers();
 document.querySelector('[data-export]')?.addEventListener('click',exportInventory);
}
function bindSortRemovers(){document.querySelectorAll('[data-remove-output]').forEach(b=>b.onclick=()=>{const rows=document.querySelectorAll('.sort-output-row');if(rows.length>1)b.closest('.sort-output-row').remove()})}
async function act(fn,message){try{await fn();toast(message);await loadData()}catch(e){toast(e.message,'bad')}}
async function handleForm(e){
 e.preventDefault();const f=e.currentTarget,a=f.dataset.action,v=Object.fromEntries(new FormData(f));try{
  let result;
  if(a==='start-delivery')result=await post('/api/deliveries',{supplierCode:v.supplierCode,sessionId:await ensureSession()});
  if(a==='receive'){const container=scannedContainer(v.containerCode,f.elements.containerCode);result=await post('/api/receiving',{supplier:f.dataset.supplier,deliveryId:f.dataset.delivery,product:v.product,grade:v.grade,size:v.size,weightKg:Number(v.weightKg),containerId:container.id,sessionId:await ensureSession()})}
  if(a==='move')result=await post('/api/movements',{...v,sessionId:await ensureSession()});
  if(a==='container')result=await post('/api/containers',{...v,capacityKg:Number(v.capacityKg)});
  if(a==='assign-container'){const container=scannedContainer(v.destinationContainerCode,f.elements.destinationContainerCode);result=await post(`/api/containers/${container.id}/assign`,{batchId:v.batchId,sessionId:await ensureSession()})}
  if(a==='transform'){const container=scannedContainer(v.containerCode,f.elements.containerCode),scanKey=['FREEZE','FREEZE_DRY'].includes(v.process)?'trayId':'containerId';result=await post('/api/transforms',{process:v.process,inputs:[{batchId:v.batchId,consumeWeightKg:Number(v.consumeWeightKg)}],outputWeightKg:Number(v.outputWeightKg),product:v.product,grade:v.grade,[scanKey]:container.id,sessionId:await ensureSession()})}
  if(a==='sorting'){const container=scannedContainer(v.containerCode,f.elements.containerCode),rows=[...f.querySelectorAll('.sort-output-row')],outputs=rows.map(row=>({grade:row.querySelector('[name="outputGrade"]').value,size:row.querySelector('[name="outputSize"]').value,weightKg:Number(row.querySelector('[name="outputWeight"]').value)})),available=Number((state.data.inventory?.items||[]).find(x=>x.id===v.batchId)?.weightKg||0),total=outputs.reduce((n,x)=>n+x.weightKg,0);if(outputs.some(x=>!x.grade||!x.size||!(x.weightKg>0)))throw Error('گرید، اندازه و وزن همه خروجی‌ها الزامی است');if(total>available)throw Error('مجموع وزن خروجی‌ها از وزن موجود بچ بیشتر است');result=await post('/api/sorting',{batchId:v.batchId,containerId:container.id,outputs,sessionId:await ensureSession()})}
  if(a==='cycle'){const container=scannedContainer(v.cycleContainerCode,f.elements.cycleContainerCode),config=(state.data.configurations?.items||[]).find(x=>x.scope==='STATION_MACHINES'&&x.status==='ACTIVE')?.values||{},machineId=config[v.type]||config[v.type.toLowerCase()];if(!machineId)throw Error(`شناسه ثابت ماشین ${v.type} در تنظیمات فعال ثبت نشده است`);result=await post('/api/cycles',{type:v.type,machineId,sessionId:await ensureSession(),...(v.type==='DRY'?{containerIds:[container.id]}:{trayIds:[container.id]})})}
  if(a==='master-create')result=await post(`/api/master-data/${v.type}`,{code:v.code,name:v.name});
  if(a==='harvest-create')result=await post('/api/harvest-periods',{code:v.code,label:v.label,startDate:v.startDate,endDate:v.endDate});
  if(a==='user-role')result=await post(`/api/users/${v.userId}/roles`,{roleCode:v.roleCode});
  if(a==='user-skill')result=await post(`/api/users/${v.userId}/skills`,{skillId:v.skillId});
  if(a==='skill-create')result=await post('/api/skills',{code:v.code,name:v.name});
  if(a==='role-create'){const permissions=[...f.querySelectorAll('[name="permissions"]:checked')].map(x=>x.value);if(!permissions.length)throw Error('حداقل یک مجوز انتخاب کنید');result=await post('/api/roles',{code:v.code,name:v.name,permissions})}
  if(a==='quality')result=await post('/api/quality-checks',{...v,inspectorId:actor()});
  if(a==='release')result=await post('/api/quality-checks/release',{...v,inspectorId:actor()});
  if(a==='package')result=await post('/api/packages',{type:v.type,level:v.level,sessionId:await ensureSession(),...(v.childPackageId?{childPackageIds:[v.childPackageId]}:{items:[{batchId:v.batchId,weightKg:Number(v.weightKg)}]})});
  if(a==='shipment')result=await post('/api/shipments',{destinationSite:v.destinationSite,packageIds:[v.packageId]});
  if(a==='transfer')result=await post('/api/internal-transfers/receive',{manifest:JSON.parse(v.manifest),receivedBy:actor(),sessionId:await ensureSession()});
  if(a==='task')result=await post('/api/tasks',{...v,priority:Number(v.priority)});
  if(a==='trace'){const batch=(state.data.inventory?.items||[]).find(x=>x.code===v.code.trim());if(!batch)throw Error('کد بچ پیدا نشد');const trace=await request('/api/trace/'+batch.id);$('#traceResult').innerHTML=traceView(trace);return}
  if(a==='config')result=await post('/api/configurations',{scope:v.scope,values:JSON.parse(v.values),userId:actor()});
  if(a==='override')result=await post('/api/overrides',{...v,requestedBy:actor()});
  toast(result?.code?`${result.code} با موفقیت ثبت شد`:'عملیات با موفقیت ثبت شد');await loadData();
 }catch(err){toast(err.message,'bad')}
}
function traceView(t){return `<div class="trace-card"><div class="trace-root"><span>بچ فعلی</span><h3>${esc(t.batch.code)}</h3><p>${esc(t.batch.product)} · ${fa(t.batch.weightKg)} kg</p>${status(t.batch.status)}</div><div class="trace-lines">${t.ancestors.length?t.ancestors.map(a=>`<article><span>↑</span><div><b>${esc(a.code)}</b><small>${esc(a.process||'RECEIVING')} · ${fa(a.weightKg)} kg</small></div></article>`).join(''):empty('این بچ ورودی اولیه است')}</div><div class="two-col">${panel('اندازه‌گیری‌ها',table(['وزن','دلیل','زمان'],t.measurements.map(m=>`<tr><td>${fa(m.weightKg)} kg</td><td>${esc(m.reason)}</td><td>${dt(m.measuredAt)}</td></tr>`)))}${panel('جابه‌جایی‌ها',table(['از','به','زمان'],t.movements.map(m=>`<tr><td>${esc(m.from)}</td><td>${esc(m.to)}</td><td>${dt(m.movedAt)}</td></tr>`)))}</div></div>`}
async function loadCloud(){try{const [health,summary]=await Promise.all([fetch(CLOUD+'/health').then(r=>r.json()),fetch(CLOUD+'/api/summary').then(r=>r.json())]);$('#cloudContent').innerHTML=`<div class="cloud-hero"><span>☁</span><div><h2>StoreMesh Cloud Control</h2><p>دید یکپارچه بدون دخالت در عملیات محلی سایت‌ها</p></div>${status(health.status==='ok'?'ACTIVE':'FAILED')}</div><div class="site-grid">${['IRAN','DUBAI','ROME'].map(s=>{const x=summary.sites?.[s]||{};return `<article><div><span class="flag">${{IRAN:'IR',DUBAI:'AE',ROME:'IT'}[s]}</span>${status(x.lastSync?'CONNECTED':'PENDING')}</div><h3>${s}</h3><b>${fa(x.events||0)}</b><small>رویداد همگام‌شده</small><p>آخرین ارتباط: ${dt(x.lastSync)}</p></article>`}).join('')}</div>`}catch(e){$('#cloudContent').innerHTML=empty('Cloud در این اجرای محلی فعال نیست')}}
function exportInventory(){const rows=state.data.inventory?.items||[],csv=['code,product,grade,size,weightKg,zone,status',...rows.map(x=>[x.code,x.product,x.grade,x.size,x.weightKg,x.zone,x.status].join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='storemesh-inventory.csv';a.click();URL.revokeObjectURL(a.href)}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.currentTarget)),r=await request('/api/auth/login',{method:'POST',body:JSON.stringify(v)});state.token=r.token;sessionStorage.token=r.token;$('#loginDialog').close();await loadData()}catch(err){$('#loginError').textContent=err.message}});
addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'dashboard';render();if(state.route==='cloud')loadCloud()});
if(state.token)loadData();else $('#loginDialog').showModal();
