const API=localStorage.api||'http://localhost:3000';let sessionId,token=sessionStorage.token,stock=[];const fa=n=>new Intl.NumberFormat('fa').format(n),$=s=>document.querySelector(s),key=()=>crypto.randomUUID(),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,options={}){options.headers={...(options.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})};const r=await fetch(API+path,options),j=await r.json();if(!r.ok)throw Error(j.message||j.errorCode);return j.data??j}
const post=(path,body,idempotency=key())=>request(path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotency},body:JSON.stringify(body)});
async function refresh(){try{await request('/health');$('#health').textContent='سایت آنلاین';if(!token)return;const[inv,jobs,tasks]=await Promise.all([request('/api/inventory'),request('/api/print-jobs'),request('/api/tasks')]);stock=inv.items;$('#workspace').hidden=false;$('#batchCount').textContent=fa(stock.length);$('#totalWeight').textContent=fa(stock.reduce((n,x)=>n+x.weightKg,0));$('#printCount').textContent=fa(jobs.items.filter(x=>x.status==='PENDING').length);$('#inventory').innerHTML=stock.map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.product)}</td><td>${esc(x.grade)}</td><td>${fa(x.weightKg)}</td><td>${esc(x.zone)}</td><td>${esc(x.status)}</td></tr>`).join('');$('#tasks').innerHTML=tasks.items.length?tasks.items.map(x=>`<div><span>${esc(x.title)}<small> ${esc(x.zone)} · ${esc(x.status)}</small></span>${x.status==='OPEN'?`<button data-task="${esc(x.id)}">شروع</button>`:''}</div>`).join(''):'<p>کاری در صف نیست.</p>';$('#prints').innerHTML=jobs.items.length?jobs.items.map(x=>`<div><span>${esc(x.label)}<small> ${esc(x.status)}</small></span>${x.status==='PENDING'?`<button data-print="${esc(x.id)}">چاپ شد</button>`:''}</div>`).join(''):'<p>چاپی در صف نیست.</p>'}catch(e){$('#health').textContent='قطع ارتباط یا دسترسی';$('#message').textContent=e.message}}
async function ensureSession(){if(!sessionId)sessionId=(await post('/api/sessions',{operatorId:'web-operator'})).id;return sessionId}
$('#login').addEventListener('submit',async e=>{e.preventDefault();try{const credentials=Object.fromEntries(new FormData(e.target)),result=await request('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)});token=result.token;sessionStorage.token=token;$('#identity').textContent=`واردشده: ${credentials.username}`;await refresh()}catch(err){$('#identity').textContent=err.message}});
$('#receive').addEventListener('submit',async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));data.weightKg=Number(data.weightKg);data.sessionId=await ensureSession();const b=await post('/api/receiving',data);$('#message').textContent=`بچ ${b.code} ثبت شد.`;await refresh()}catch(err){$('#message').textContent=err.message}});
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));data.priority=Number(data.priority);await post('/api/tasks',data);$('#message').textContent='Task ایجاد شد';await refresh()}catch(err){$('#message').textContent=err.message}});
$('#qualityForm').addEventListener('submit',async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target)),batch=stock.find(x=>x.code===data.batchCode);if(!batch)throw Error('Batch پیدا نشد');await post('/api/quality-checks',{batchId:batch.id,result:data.result,notes:data.notes,inspectorId:'web-user'});$('#message').textContent='نتیجه QC ثبت شد';await refresh()}catch(err){$('#message').textContent=err.message}});
$('#traceForm').addEventListener('submit',async e=>{e.preventDefault();try{const code=new FormData(e.target).get('batchCode'),batch=stock.find(x=>x.code===code);if(!batch)throw Error('Batch پیدا نشد');const trace=await request(`/api/trace/${batch.id}`);$('#trace').textContent=JSON.stringify(trace,null,2)}catch(err){$('#trace').textContent=err.message}});
document.addEventListener('click',async e=>{try{if(e.target.dataset.task){await post(`/api/tasks/${e.target.dataset.task}/claim`,{operatorId:'web-operator'});await refresh()}if(e.target.dataset.print){await request(`/api/print-jobs/${e.target.dataset.print}/complete`,{method:'POST'});await refresh()}}catch(err){$('#message').textContent=err.message}});refresh();setInterval(refresh,5000);
